"""initial_migration

Revision ID: 994dac5e81a5
Revises:
Create Date: 2025-05-21 09:24:21.170301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "994dac5e81a5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "filescan",
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("md5_hash", sa.String(), nullable=False),
        sa.Column("sha1_hash", sa.String(), nullable=False),
        sa.Column("sha256_hash", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SCANNING", "COMPLETED", "ERROR", name="scanstatus"),
            nullable=False,
        ),
        sa.Column("scan_id", sa.String(), nullable=True),
        sa.Column("scan_date", sa.DateTime(), nullable=True),
        sa.Column("result_date", sa.DateTime(), nullable=True),
        sa.Column("positives", sa.Integer(), nullable=True),
        sa.Column("total_scans", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.pkid"],
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_filescan_filename"), "filescan", ["filename"], unique=False
    )
    op.create_index(
        op.f("ix_filescan_md5_hash"), "filescan", ["md5_hash"], unique=False
    )
    op.create_index(
        op.f("ix_filescan_sha1_hash"), "filescan", ["sha1_hash"], unique=False
    )
    op.create_index(
        op.f("ix_filescan_sha256_hash"), "filescan", ["sha256_hash"], unique=False
    )
    op.create_index(op.f("ix_filescan_user_id"), "filescan", ["user_id"], unique=False)
    op.create_table(
        "token",
        sa.Column("pkid", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("token_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.pkid"],
        ),
        sa.PrimaryKeyConstraint("pkid"),
    )
    op.create_index(
        op.f("ix_token_access_token"), "token", ["access_token"], unique=False
    )
    op.create_index(op.f("ix_token_user_id"), "token", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_user_id"), table_name="token")
    op.drop_index(op.f("ix_token_access_token"), table_name="token")
    op.drop_table("token")
    op.drop_index(op.f("ix_filescan_user_id"), table_name="filescan")
    op.drop_index(op.f("ix_filescan_sha256_hash"), table_name="filescan")
    op.drop_index(op.f("ix_filescan_sha1_hash"), table_name="filescan")
    op.drop_index(op.f("ix_filescan_md5_hash"), table_name="filescan")
    op.drop_index(op.f("ix_filescan_filename"), table_name="filescan")
    op.drop_table("filescan")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
